"""
doc_generator.py
------------------
Converts a structured outline (title + sections) into a PDF, PPTX, or DOCX file
in memory (as bytes), so it can be offered as a Streamlit download button
without ever writing to disk.

Outline format (produced by the LLM):
{
    "title": "...",
    "sections": [
        {"heading": "...", "content": "..."},
        ...
    ]
}
"""

import io
from fpdf import FPDF
from docx import Document
from pptx import Presentation


def _sanitize_for_pdf(text: str) -> str:
    """
    fpdf's default fonts only support latin-1 characters, but LLM output
    often includes smart quotes, em-dashes, or emoji. Replace anything
    unsupported instead of crashing.
    """
    return text.encode("latin-1", errors="replace").decode("latin-1")


def generate_pdf(outline: dict) -> bytes:
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 18)
    pdf.multi_cell(0, 10, _sanitize_for_pdf(outline["title"]))
    pdf.ln(4)

    for section in outline["sections"]:
        pdf.set_font("Helvetica", "B", 13)
        pdf.multi_cell(0, 8, _sanitize_for_pdf(section["heading"]))
        pdf.set_font("Helvetica", "", 11)
        pdf.multi_cell(0, 7, _sanitize_for_pdf(section["content"]))
        pdf.ln(3)

    return bytes(pdf.output())


def generate_docx(outline: dict) -> bytes:
    doc = Document()
    doc.add_heading(outline["title"], level=1)

    for section in outline["sections"]:
        doc.add_heading(section["heading"], level=2)
        doc.add_paragraph(section["content"])

    buffer = io.BytesIO()
    doc.save(buffer)
    return buffer.getvalue()


def _split_into_bullets(text: str, max_bullets: int = 5) -> list:
    """
    Splits a paragraph into short bullet points for slides.
    Simple sentence-based split - good enough for fresher-project purposes.
    """
    sentences = [s.strip() for s in text.replace("\n", " ").split(". ") if s.strip()]
    bullets = sentences[:max_bullets]
    return bullets if bullets else [text[:150]]


def generate_pptx(outline: dict) -> bytes:
    prs = Presentation()

    # Title slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    slide.shapes.title.text = outline["title"]
    if len(slide.placeholders) > 1:
        slide.placeholders[1].text = "Generated by QueAssist"

    # One slide per section
    bullet_layout = prs.slide_layouts[1]
    for section in outline["sections"]:
        slide = prs.slides.add_slide(bullet_layout)
        slide.shapes.title.text = section["heading"]
        bullets = _split_into_bullets(section["content"])

        body = slide.placeholders[1]
        text_frame = body.text_frame
        text_frame.text = bullets[0]
        for bullet in bullets[1:]:
            p = text_frame.add_paragraph()
            p.text = bullet

    buffer = io.BytesIO()
    prs.save(buffer)
    return buffer.getvalue()
